
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  dept TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 'Sales');
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', 'Accounting');
INSERT INTO EMPLOYEE VALUES (0003, 'Ava', 'Sales');

-- fetch 
SELECT * FROM EMPLOYEE WHERE dept = 'Sales';
show tables;

ALTER TABLE EMPLOYEE ADD(salary TEXT);
desc TABLE EMPLOYEE;

SELECT * FROM EMPLOYEE;
ALTER TABLE EMPLOYEE MODIFY salary INTEGER;
SELECT * FROM EMPLOYEE;
desc EMPLOYEE;
SELECT 21+14;

SELECT name FROM EMPLOYEE WHERE name like '_a%';

UPDATE EMPLOYEE SET salary = '50000' WHERE empId = 0001;
UPDATE EMPLOYEE SET salary = '55000' WHERE empId = 0002;
UPDATE EMPLOYEE SET salary = '48000' WHERE empId = 0003;


SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE salary between 40000 and 51000;

SELECT * FROM EMPLOYEE where dept in("Sales","Accounting");